### ISSUE TITLE
how to include some particular so and exclude others

### ISSUE THREAD

**Issue by svenjung** [Jween/android-soexcluder#1]
soexcluder {
    release {
        include '*_/libpl_droidsonroids_gif_'
    }
}

soexcluder {
    release {
        include '**/libpl_droidsonroids_gif.so'
        include '**/libpl_droidsonroids_gif_surface.so'
    }
}

it does not work when i want just include libpl_droidsonroids_gif.so & libpl_droidsonroids_gif_surface.so, 
such as above, it always only included ## **libpl_droidsonroids_gif.so**

**Comment by shawnlinboy** [comment]
@svenjung 敏爷。。。。这么巧你也在啊。

**Comment by Jween** [comment]
The final so path is "lib/${abi}/{soFileName.so}"
for example: lib/armeabi-v7a/foo.so

To include libpl_droidsonroids_gif.so and libpl_droidsonroids_gif_surface.so for release buildType or release flavor.

``` groovy
soexcluder {
    release {
        include '"lib/**/libpl_droidsonroids_gif.so"
        include "lib/**/libpl_droidsonroids_gif_surface.so"
    }
}
```

Note that:
*\* means matching all folder names
* means matching all charactors
