### ISSUE TITLE
Would it be possible to exclude by architecture type (defined on splits block)?

### ISSUE THREAD

**Issue by githubdoramon** [Jween/android-soexcluder#2]

**Comment by Jween** [comment]
Nope, multiple apks by splits packages just one universal apk actually, and then it splits resources by density and abi to generate multiple apk from that universal apk.
Soexcluder goes another way, it simply remove so files within each build variant while packaging, it splits by variant(flavor + buildType).

If you want to exclude by abi, you can just remove the source so files inside your libs/${abi}/ folders.
